### ISSUE TITLE
NameError: name 'generate_validation_files' is not defined while trying planet notebook.

### ISSUE THREAD

**Issue by pseudotensor** [Azure/fast_retraining#68]
LightGBM version: 2.0.5
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~/h2o4gpu/testsxgboost/04_PlanetKaggle_GPU.py in <module>()
     51 
     52 
---> 53 X_train, y_train, X_test, y_test = load_planet_kaggle()
     54 
     55 

~/h2o4gpu/testsxgboost/libs/loaders.py in load_planet_kaggle()
    212     if not os.listdir(val_path):
    213         logger.info('Validation folder is empty, moving files...')
--> 214         generate_validation_files(train_path, val_path)
    215 
    216     logger.info('Reading in labels')

NameError: name 'generate_validation_files' is not defined

Solution:  In loaders.py:

from libs.planet_kaggle import to_multi_label_dict, get_file_count, enrich_with_feature_encoding, featurise_images, generate_validation_files

**Comment by msalvaris** [comment]
@pseudotensor Thanks for spotting this. A fix has been added [https://github.com/Azure/fast_retraining/pull/71](https://github.com/Azure/fast_retraining/pull/71)
